root_web/donation/urls.py
from django.urls import path,include
from . import views

app_name = 'donation'

urlpatterns = [
    path('add_don/',views.add_don,name='add_don'),
    path('don_ind/',views.don_ind,name='don_ind'),
    path('don_bulk/',views.don_bulk,name='don_bulk'),
    path('don_anon/',views.don_anon,name='don_anon'),
    path('don_added/',views.don_added,name='don_added'),
    path('view_don/',views.DonationListView.as_view(),name = 'view_don'),
    path('download/',views.download_rec,name = 'download_rec'),
    path('edit_misc/',views.set_prefix,name = 'edit_misc'),
    path('export_donation/',views.export_donation,name = 'export_donations'),
    path('resend_mails/',views.resend_mails,name = 'resend_mail'),
    path('edit_don/',views.edit_don,name = 'edit_don')
]

root_web/root_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('supp/',include('supporters.urls')),
    path('don/',include('donation.urls')),
    path('exp/',include('expenditure.urls')),
    path('user/',include('usersreg.urls'))
]

root_web/supporters/urls.py
from django.urls import path
from . import views

app_name = 'supporters'
urlpatterns = [
    path('add_supp/',views.add_supp,name = 'add_supp'),
    path('edit_supp/',views.supp_edited,name = 'supp_edited'),
    path('supp_edited/',views.edit_supp,name = 'edit_supp'),
    path('view_supp/',views.view_supp,name = 'view_supp'),
    path('del_supp/',views.del_supp,name = 'del_supp'),
    path('deleted/',views.delete, name='deleted'),
    path('view_don/',views.view_don,name = 'view_don'),
    path('import/',views.import_supp,name = 'import'),
    path('don_details/',views.view_don,name = 'don_details'),
    path('export/',views.export_supporters,name = 'export_supporters')
    ]

root_web/donation/models.py
from django.db import models
# Create your models here.
mode_choces = [
    ('CASH', 'Cash'),
    ('INET', 'Internet Banking'),
    ('UPI', 'UPI'),
    ('IMPS', 'IMPS'),
    ('NEFT', 'NEFT'),
    ('CHEQUE', 'Cheque'),
]

class verified_donation(models.Model):
    rec_no = models.AutoField(primary_key=True)
    recipt_num = models.IntegerField(default = 0)
    member = models.ForeignKey('supporters.supporter', on_delete=models.CASCADE,null=True)
    anon_name = models.CharField(max_length = 100,null = True,blank =True)
    amount = models.CharField(max_length = 20, blank=False)
    date_donation = models.DateField(blank=False)
    mode_donation = models.CharField(max_length = 100,default = 'CASH',choices = mode_choces)
    date_rec = models.DateField()
    migrated = models.BooleanField(default = False)
    anon = models.BooleanField(default = False)
    mail_sent = models.BooleanField(default = False)


class misc(models.Model):
    rec_no_prefix = models.IntegerField(default = 0)

root_web/donation/forms.py
from django.forms import ModelForm,CharField,DateField,Form,FileField
from .models import verified_donation,misc


class IndonForm(ModelForm):
    class Meta:
        model = verified_donation
        fields = ['amount','mode_donation']


class AnondonForm(ModelForm):
    amount = CharField(required=True)
    class Meta:
        model = verified_donation
        fields = ['anon_name','amount','mode_donation']


class miscForm(ModelForm):
    class Meta:
        model = misc
        fields = ['rec_no_prefix']
    


class Uploadfiles(Form):
    file = FileField()

root_web/donation/views.py
from django.shortcuts import render,redirect
from supporters.models import supporter
from .forms import IndonForm,AnondonForm
from .models import verified_donation,misc
from django.utils import timezone
from datetime import datetime
from django.views.generic.list import ListView
from django.http import FileResponse
from os import remove
import zipfile
from django.core.mail import EmailMessage
# Create your views here.
from reportlab.pdfgen import canvas
import os
from django.contrib.auth.decorators import login_required
from num2words import num2words
from . import forms
from openpyxl import Workbook
from usersreg.models import member
from django.core.paginator import Paginator


def hello(f_name,rec_no,name,amount,mode,date,date_rec):
    print(f_name,rec_no,name,amount,mode,date,date_rec)
    c = canvas.Canvas(f_name)
    c.drawInlineImage("donform.jpeg", 40, 20,510,770)
    c.drawString(75,637,str(rec_no))
    c.drawString(75, 530, name)
    #c.drawString(475, 637, str(date_rec))
    c.drawString(265, 492, str(amount)   )
    c.drawString(170, 474, (str(num2words(amount))).capitalize())
    c.drawString(320, 318, 'U80211PB2017NPL046830')
    c.drawString(320, 285, 'AAECH2743L')
    c.drawString(320, 255, '8437833465')
    c.drawString(95, 318, mode)
    c.drawString(95, 284, str(date))
    c.save()


@login_required
def add_don(request):
    mem = member.objects.get(user = request.user)
    return render(request,'donation/add_don.html',{"member":mem})


@login_required
def don_ind(request):
    mem = member.objects.get(user = request.user)
    if request.method=="GET":
        supp = supporter.objects.all()
        return render(request,'donation/don_ind.html',{"message":"0","supp":supp})
    else:
        obj = request.POST["supp_name"]
        phone = int(obj.split(",")[1])
        obj = supporter.objects.get(phone_no = phone)
        form = IndonForm()
        return render(request,'donation/don_ind.html',{"message":"hello","supporter":obj,'form':form,'member':mem})


@login_required
def don_bulk(request):
    mem = member.objects.get(user = request.user)
    month = timezone.localdate().month
    year = timezone.localdate().year
    if request.method == "GET":
        try:
            type = request.GET["typea"]
            try:
                if type == "si":
                    supp= supporter.objects.filter(is_si = True)
                elif type == "cons":
                    supp = supporter.objects.filter(is_constant = True)
                elif type == "res":
                    supp = supporter.objects.filter(resources = True)
                elif type == "spon":
                    supp = supporter.objects.filter(is_sponsor = True)
                elif type == "onetime":
                    supp = supporter.objects.filter(is_one_time=True)
                else:
                    supp = supporter.objects.all()
            except:
                print("error inie")
        except:
            supp = supporter.objects.all()
            type='all'
        paginator  = Paginator(supp,20)
        page = request.GET.get("page")
        supporters = paginator.get_page(page)
    return render(request,'donation/don_bulk.html',{"supp":supporters,"month":month,"year":year,'member':mem,'type':type})


@login_required
def don_anon(request):
    mem = member.objects.get(user = request.user)
    if request.method=="GET":
        form = AnondonForm()
        return render(request,'donation/don_anon.html',{"form":form,'member':mem})
    if request.method == "POST":
        form = AnondonForm(request.POST)
        amount = request.POST['amount']
        date = request.POST['date_donation']
        mode = request.POST['mode_donation']
        date_rec = timezone.now()
        anon_don = verified_donation(amount =  amount , date_donation = date , mode_donation = mode , anon = True,date_rec = date_rec)
        anon_name_set=False    
        if 'anon_name' in form.changed_data:
            anon_name_set = True
            anon_don.anon_name = request.POST['anon_name']
        anon_don.save()
        anon_don.recipt_num = index_rec_no(anon_don.rec_no)
        anon_don.save()
        if anon_name_set:
            f_name = [str(anon_don.anon_name)+str(anon_don.recipt_num)+'.pdf']
        else:
            f_name = ['No Name -'+str(anon_don.recipt_num)+'.pdf']        
            
        hello(f_name[0],anon_don.recipt_num,str(anon_don.anon_name),anon_don.amount,anon_don.mode_donation,anon_don.date_donation,anon_don.date_rec)
        try:            #check if save is checked by user
            if request.POST['mail']:
                if len(request.POST['email_id'])>0:
                    send_mail_A([str(request.POST["email_id"])],f_name[0],str(anon_don.anon_name))
                else:
                    send_mail_A(['Kalamenrichinglives@gmail.com'],f_name[0],str(anon_don.anon_name))
        except:
            pass
        try:
            if request.POST["save"]==True:    
                view_val = 'added'
        except:
            os.remove(f_name[0])
            view_val = 'added_none'
            f_name = 'NONE'
            
        values = [[anon_don.recipt_num,anon_don.anon_name, anon_don.amount, anon_don.date_donation, anon_don.mode_donation,anon_don.date_rec,anon_don.migrated]]
        return render(request,'donation/don_added.html',{"values":values,"f_name":f_name,"view":view_val,'member':mem})


@login_required
def don_added(request):
    mem = member.objects.get(user = request.user)
    if request.POST["type"]=="0":
        supp = supporter.objects.get(pk = int(request.POST["pk"]))
        rec = verified_donation(member = supp ,
                                amount = request.POST["amount"],
                                date_donation = request.POST["date_donation"],
                                mode_donation = request.POST["mode_donation"],
                                date_rec = timezone.now())
        rec.save()
        rec.recipt_num  = index_rec_no(rec.rec_no)
        rec.save()
        f_name = [str(rec.member.name)+str(rec.recipt_num)+'.pdf']
        hello(f_name[0],rec.recipt_num,rec.member.name,rec.amount,rec.mode_donation,rec.date_donation,rec.date_rec)
        try:
            if request.POST['mail']:
                if supp.email_id == None:
                    email = request.POST["email_id"]
                    if len(email)>0:
                        send_mail_A([email],f_name[0],rec.member.name)
                    else:
                        print('mail id not valid')
                else:
                    send_mail_A([supp.email_id],f_name[0],rec.member.name)
        except:
            pass

        try:            #check if save is checked by user
            if request.POST['save']:
                view_val = 'added'
                pass
        except:
            os.remove(f_name[0])
            view_val = 'added_none'
            f_name = 'NONE'
        values = [[rec.recipt_num,rec.member.name, rec.amount, rec.date_donation, rec.mode_donation,rec.date_rec,rec.migrated]]
    
    
    if request.POST["type"]=="1":
        abc = list(request.POST.keys())
        choices = []
        dates = []
        values = []
        f_name=[]
        saves = []
        mails = []
        for choice in abc:
            if 'choice' in choice:
                choices.append(choice.strip('choice'))
            if 'recipt' in choice:
                saves.append(choice.strip('recipt'))
            if 'mail' in choice:
                mails.append(choice.strip('mail'))
        for j in choices:
            dates.append(request.POST['date' + j])
        dates.sort(key=lambda date: datetime.strptime(date, '%Y-%m-%d'))
        sorted_choices = []
        for i in choices:
            date = dates.pop(0)
            for j in choices:
                if j not in sorted_choices:
                    if date == request.POST['date' + j]:
                        sorted_choices.append(j)
        for i in sorted_choices:
            member_id = (request.POST['choice'+i])
            mem = supporter.objects.get(pk=member_id)
            don = verified_donation(member=mem)
            amount = request.POST['amount' + i]
            don.amount = amount
            don.date_donation = request.POST['date'+i]
            don.date_rec = timezone.now()
            don.mode_donation = request.POST['mode'+i]
            don.save()
            don.recipt_num = index_rec_no(don.rec_no)
            don.save()
            f_name.append(str(don.member.name)+str(don.recipt_num)+'.pdf')
            hello(f_name[-1],don.recipt_num,don.member.name,don.amount,don.mode_donation,don.date_donation,don.date_rec)
            if i in mails:
                if mem.email_id == None:
                    send_mail_A(['arwindersngh62@gmail.com'],f_name[-1],don.member.name)
                else:
                    send_mail_A([mem.email_id],f_name[-1],don.member.name)
            if i not in saves:    
                os.remove(f_name[-1])
                f_name.pop()

            values.append([don.recipt_num,don.member.name, don.amount, don.date_donation, don.mode_donation, don.date_rec,don.migrated])
        if len(saves)>0:
            view_val = 'added'
        else:
            view_val = 'added_none'
    return render(request,'donation/don_added.html',{"values":values,"f_name":f_name,"view":view_val,'member':mem})


class DonationListView(ListView):
    #user = self.request.user
    #mem = member.objects.get(user = user)
    model = verified_donation
    paginate_by = 50  # if pagination is desired


@login_required
def download_rec(request):
    allkeys =  list(request.POST.keys())
    files = []
    for i in allkeys:
        if 'file' in i:
            files.append(i)
    if len(files)>1:
        zipoj = zipfile.ZipFile('filled.zip', 'w')
        for file in files:
            zipoj.write(request.POST[file])
        zipoj.close()
        zip_file = open('filled.zip', 'rb')
    else:

root_web/templates/donation/add_don.html
{% extends 'users/index.html' %}
{% block content %}
<style>
      .options a{
      display:block;
      background-color: white;
      padding:5px;
      text-align:center;
      border:2px solid #2460A7FF;
      width:30%;
      height:5%;
      margin-left:20%;
      margin-top:5%;
      }
</style>
<div class="options">
      <a href="{% url 'donation:don_ind' %}">Individual</a>
      <a href="{% url 'donation:don_anon' %}">Anonymous</a>
      <a href="{% url 'donation:don_bulk' %}">Bulk</a>
</div>
{% endblock %}

root_web/templates/donation/don_added.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table, th, td{
    border:1px solid black;
    }
    td,th {
    padding:10px;
    }
</style>

<table >
    <tr>
        <th>Recipt No.</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Donation Date</th>
        <th>Mode</th>
        <th>Recipt Date</th>
        <th>Migrated</th>
    </tr>
    {% for value in values %}
        <tr>
            {% for part in value %}
                <td>{{part}}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
{% if view == 'details' %}
<h1 style="text-align:center;">Total Donation Amount = {{total}}</h1>
{% endif %}
{% if view == 'added'%}
<form method = "POST" action="{% url 'donation:download_rec' %}" target="_blank">
{% csrf_token %}
{% for file_name in f_name %}
<input type="text" hidden value="{{file_name}}" name="file{{forloop.counter}}">
{% endfor %}
{%if view != 'added_none' %}
<input type="submit" value="Download Recipt">
{% endif %}
</form>
{% endif %}
{% endblock %}

root_web/templates/donation/don_anon.html
{% extends 'users/index.html' %}
{% block content %}
<form action="{%url 'donation:don_anon' %}" method="POST">
    {% csrf_token %}
    <table>
        <input type="hidden" name = "type" id="type" value="2">
        {{form.as_table}}
    <tr>
        <th><label for = "date_donation" >Date Of Donation</label></th>
        <td><input type = "date" name = "date_donation" id = "date_donation" required></td>
    </tr>
    <tr>
        <th><label for="mail"> Send Mail</label></th>
        <td><input type="checkbox" name="mail" id = "mail" value="True"></td>
    </tr>
    <tr>
        <th><label for="email_id">Email(optional)</label></th>
        <td><input type="email" name="email_id" id = "email_id"></td>
    </tr>
    <tr>
        <th><label for="save">Save Recipt</label></th>
        <td><input type="checkbox" name="save" id = "save" value="True"></td>
    </tr>
    <tr>
        <td>
            <input style = "width:100%;" type="submit" value="Submit">
        </td>
    </tr>
    </table>
</form>
{% endblock %}

root_web/templates/donation/don_bulk.html
{% extends 'users/index.html' %}
{% block content %}
<style>
    .inner td{ border: 1px solid;}
</style>
<form action = "{% url 'donation:don_bulk' %}" method="GET">
    <table>
        <tr>
            <td>
                <label for="typea">Select the type to fetch</label>
            </td>
            <td>
                <select id="typea" name="typea">
                    <option value="none">None</option>
                    <option value="all">ALL</option>
                    <option value="si">Standard Instruction</option>
                    <option value="cons">Constant</option>
                    <option value="res">Resources</option>
                    <option value="spon">Sponsor</option>
                    <option value="onetime">One-Time</option>
                </select>
            </td>
            <td>
                <label for="all">All</label>
                <input type="checkbox" name="all" id="all" value="true">
            </td>
            <td>
                <input type = "submit" value = "Get" style="width:100%;border-radius:0px;">
            </td>

        </tr>
    </table>
</form>
<form action = "{% url 'donation:don_added' %}" method="POST">
{% csrf_token %}
    <input type="hidden" name = "type" id="type" value="1">
<table class="inner" style = "width:10%;">
    <tr>
    <th>Please Select</th>
    <th>Name</th>
    <th>Phone Number</th>
    <th>City</th>
    <th>Amount</th>
    <th>Mode</th>
    <th>Donation Date</th>
    <th>Generate Recipt</th>
    <th>Send Mail</th>
</tr>
{% for choice in supp%}
<tr>
    <td><input type = "checkbox" name="choice{{choice.id}}" id = "choice{{choice.id}}" value = "{{choice.id}}"></td>
    <td><label for = "choice{{choice.id}}" >{{choice.name}}</label></td>
    <td><label for = "choice{{choice.id}}" >{{choice.phone_no}}</label></td>
    <td><label for = "choice{{choice.id}}" >{{choice.city}}</label></td>
    {% if choice.is_constant == True %}
        <td><input style="width:50px;" type="number" id="amount{{choice.id}}" name="amount{{choice.id}}" value = "{{choice.amount}}"></td>
    {% else %}
        <td><input style="width:50px;" type="number" id="amount{{choice.id}}" name="amount{{choice.id}}" placeholder="amount"></td>
    {% endif %}
    <td><select  style="width:80px;" id="mode{{choice.id}}" name="mode{{choice.id}}">
    {% if choice.is_si == True %}
        <option value="inb">Internet Banking</option>
        <option value="ca">Cash</option>
    {% else %}
        <option value="ca">Cash</option>
        <option value="inb">Internet Banking</option>
    {% endif %}
      <option value="chq">Cheque</option>
      <option value="upi">UPI</option>
      <option value="neft">NEFT</option>
      <option value="imps">IMPS</option>

    </select></td>
    {% if choice.is_si == True %}

        {% if choice.si_date < 10 %}
            {% if month < 10 %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-0{{month}}-0{{choice.si_date}}" ></td>
            {% else %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-{{month}}-0{{choice.si_date}}" ></td>
            {% endif %}
        {% endif %}
        {% if choice.si_date > 9 %}
            {% if month < 10  %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-0{{month}}-{{choice.si_date}}" ></td>
            {% else %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-{{month}}-{{choice.si_date}}" ></td>
            {% endif %}
        {% endif %}
    {% endif %}
    {% if choice.is_si != True %}
        <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" ></td>
    {% endif %}
    <td><input type = "checkbox" name="recipt{{choice.id}}" id = "recipt{{choice.id}}" value = "{{choice.id}}"></td>
    <td><input type = "checkbox" name="mail{{choice.id}}" id = "mail{{choice.id}}" value = "{{choice.id}}"></td>
</tr>
{% endfor %}
</table>
<input type = "submit" value = "Add Donation">
</form>
<div class = "pagination">
    <span class="step_links">
        {% if supp.has_previous %}
            <a href="?page=1&typea={{type}}">&laquo; First</a>
            <a href="?page={{ supp.previous_page_number}}&typea={{type}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{supp.number}} of {{supp.paginator.num_pages}}
        </span>
        {% if supp.has_next %}
            <a href="?page={{supp.paginator.num_pages}}&typea={{type}}">Last &raquo;</a>
            <a href="?page={{supp.next_page_number}}&typea={{type}}">Next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

root_web/templates/donation/don_ind.html
{% extends 'users/index.html' %}
{% block content %}
{% if message == '0' %}
<form  method="POST">
{% csrf_token %}

<label for="name">Name</label>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
{% for choice in supp%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
<input type="submit" value="Submit">
</form>
{% else %}
<form action="{% url 'donation:don_added' %}" method="post">

   {% csrf_token %}
  <table style="text-align:right;">

  <input type="hidden" name = "type" id="type" value="0">
  <input type="hidden" name="pk" id="pk" value="{{supporter.pk}}">
    <tr>
      <th>Name:</th><td>{{supporter.name}}</td>
    </tr>
    <tr>
      <th>Phone:</th><td>{{supporter.phone_no}}</td>
    </tr>
    <tr>
      <th>City:</th><td>{{supporter.city}}</td>
    </tr>
    <tr>
      <th>email:</th><td>{{supporter.email}}</td>
    </tr>
  {{form.as_table}}
  <tr>
  <th><label for = "date_donation">Date Of Donation</label></th>
  <td>
  <input type = "date" name = "date_donation" id = "date_donation">
  </td>
  </tr>
    <tr>
        <th><label for="mail"> Send Mail</label></th>
        <td><input type="checkbox" name="mail" id = "mail" value="True"></td>
    </tr>
    <tr>
        <th><label for="email_id">Email(if not present)</label></th>
        <td><input type="email" name="email_id" id = "email_id"></td>
    </tr>
    <tr>
        <th><label for="save">Save Recipt</label></th>
        <td><input type="checkbox" name="save" id = "save" value="True"></td>
    </tr>
  <tr>
    <td>
  <input style = "width:100%;" type="submit" value="Submit">
    </td>
  </tr>
  </table>
</form>
{% endif %}
{% endblock %}

root_web/templates/donation/edit_don.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table,th,td {
border:2px solid lightgreen;
border-collapse: collapse;
}
</style>
<form method="POST">
{%csrf_token%}
<table >
	<tr>
	<th>Reciept No</th>
	<th>Member Name</th>
	<th>Amount</th>
	<th>Date of Donation</th>
	<th>Date of Reciept</th>
	<th>Mode of Donation</th>
	<th>Mail Sent</th>
	<th>Select</th>
	</tr>
	{% for dons in don %}
	<tr>
	<td>{{dons.recipt_num}}</td>
	<td>{{dons.member.name}}</td>
	<td>{{dons.amount}}</td>
	<td>{{dons.date_donation}}</td>
	<td>{{dons.date_rec}}</td>
	<td>{{dons.mode_donation}}</td>
	<td>{{dons.mail_sent}}</td>
	<td><button type="submit" name="value" value ={{dons.rec_no}}>Edit</a></td>
	</tr>
	{% endfor %}
</table>
</form>
<div class = "pagination">
    <span class="step_links">
        {% if supp.has_previous %}
            <a href="?page=1&typea={{type}}">&laquo; First</a>
            <a href="?page={{ supp.previous_page_number}}&typea={{type}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{supp.number}} of {{supp.paginator.num_pages}}
        </span>
        {% if supp.has_next %}
            <a href="?page={{supp.paginator.num_pages}}&typea={{type}}">Last &raquo;</a>
            <a href="?page={{supp.next_page_number}}&typea={{type}}">Next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

root_web/templates/donation/edit_misc.html
{% extends 'users/index.html' %}
{% block content %}
<form method = "POST" action="{% url 'donation:edit_misc' %}">
{% csrf_token %}
Current Value : {{value}} <br>
{{form}}
<input type = Submit value = "Submit">
</form>
{% endblock %}

root_web/templates/donation/import.html
{% extends 'users/index.html' %}
{% block content %}
<form action="{% url 'supporters:import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>
{% endblock %}

root_web/templates/donation/resend_mail.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table,th,td {
border:2px solid lightgreen;
border-collapse: collapse;
}
</style>
<form method="POST">
{%csrf_token%}
<table >
	<tr>
	<th>Reciept No</th>
	<th>Member Name</th>
	<th>Amount</th>
	<th>Date of Donation</th>
	<th>Date of Reciept</th>
	<th>Mode of Donation</th>
	<th>Mail Sent</th>
	<th>Select</th>
	</tr>
	{% for dons in don %}
	<tr>
	<td>{{dons.recipt_num}}</td>
	<td>{{dons.member.name}}</td>
	<td>{{dons.amount}}</td>
	<td>{{dons.date_donation}}</td>
	<td>{{dons.date_rec}}</td>
	<td>{{dons.mode_donation}}</td>
	<td>{{dons.mail_sent}}</td>
	<td><input type = "checkbox" name="check{{dons.rec_no}}"></td>
	</tr>
	{% endfor %}
</table>
<input type="submit">
</form>
{% endblock %}

root_web/templates/donation/verified_donation_list.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table, th, td{
    border:1px solid black;
    }
    td,th {
    padding:10px;
    }
</style>
<table>
	<tr>
	<th> Recipt Number</th>
	<th>Name</th>
	<th>Amount</th>
	<th>Donation Date</th>
	<th>Donation Mode</th>
	<th>Recipt Date</th>
	<th>Migrated </th>
	</tr>

    {% for i in object_list %}
    <tr>
    <td>{{ i.rec_no }}</td>
    {% if i.anon == "True" %}
    	<td>{{ i.anon_name }}</td>
    {% else %}
    	<td>{{ i.member.name }}</td>
    {% endif %}
    <td>{{ i.amount }}</td>
    <td>{{ i.date_donation }}</td>
    <td>{{ i.mode_donation }}</td>
    <td>{{ i.date_rec }}</td>
    <td>{{ i.migrated }}</td>
    </tr>
    {% endfor %}

</table>
<nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
{% endblock %}