root_web/donation/urls.py
from django.urls import path,include
from . import views

app_name = 'donation'

urlpatterns = [
    path('add_don/',views.add_don,name='add_don'),
    path('don_ind/',views.don_ind,name='don_ind'),
    path('don_bulk/',views.don_bulk,name='don_bulk'),
    path('don_anon/',views.don_anon,name='don_anon'),
    path('don_added/',views.don_added,name='don_added'),
    path('view_don/',views.DonationListView.as_view(),name = 'view_don'),
    path('download/',views.download_rec,name = 'download_rec'),
    path('edit_misc/',views.set_prefix,name = 'edit_misc'),
    path('export_donation/',views.export_donation,name = 'export_donations'),
    path('resend_mails/',views.resend_mails,name = 'resend_mail'),
    path('edit_don/',views.edit_don,name = 'edit_don')
]

root_web/expenditure/urls.py
from django.urls import path
from . import views

app_name = 'expenditure'
urlpatterns=[
    path('addexp/',views.add_exp_view,name = 'add_exp'),
    path('addadv/',views.add_adv,name = 'add_adv'),
    path('expgen/',views.generate_exp,name = 'gen_exp'),
    path('clearexp/',views.clear_exp,name = 'clearexp'),
    path('approvexp/',views.approve_exp,name = 'approvexp'),
    path('myexp/',views.my_exp,name = 'myexp'),
    path('viewexp/',views.view_exp,name = 'viewexp')
]

root_web/root_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('supp/',include('supporters.urls')),
    path('don/',include('donation.urls')),
    path('exp/',include('expenditure.urls')),
    path('user/',include('usersreg.urls'))
]

root_web/expenditure/models.py
from django.db import models
from usersreg.models import member
from django.utils import timezone


choices = [
    ('prog','Program Cost'),
    ('admin','Administrative Cost'),
    ('funds','Fundraising Cost')
]


choices_sub = []
choices_cat=[]

class advanced(models.Model):
    adv_id = models.IntegerField(primary_key=True)
    added_by = models.ForeignKey(member,on_delete=models.CASCADE)
    event_name = models.CharField(max_length=250)
    adv_desc = models.CharField(max_length=1000)
    event_date = models.DateField()
    added_on = models.DateField(default = timezone.now())
    is_cleared = models.BooleanField(default = False)
    status = models.CharField(max_length=250,default= 'Submitted')
    is_attached = models.BooleanField(default = False)
    amount = models.DecimalField(default=0,decimal_places=2,max_digits=15)
    amount_paid = models.DecimalField(default=0,decimal_places=2,max_digits=15)

class expenditure(models.Model):
    reimb_id = models.IntegerField(primary_key=True)
    added_by = models.ForeignKey(member,on_delete=models.CASCADE,default=None)
    event_name = models.CharField(max_length=250, null=True, blank=True)
    event_desc = models.CharField(max_length=250,choices=choices)
    event_date = models.DateField()
    bill_amount = models.DecimalField(default=0,decimal_places=2,max_digits=15)
    paid_amount = models.DecimalField(default=0,decimal_places=2,max_digits=20)
    bill_no = models.CharField(max_length=250)
    bill_date = models.DateField(default = timezone.now())
    vendor_name = models.CharField(max_length=250)
    is_advanced = models.BooleanField(default=False)
    adv_id = models.ForeignKey(advanced,on_delete=models.CASCADE)
    adv_amount = models.DecimalField(default=0,decimal_places=3,max_digits=8)
    is_approved = models.BooleanField(default=False)
    is_cleared = models.BooleanField(default=False)
#    amount_cleared = DecimalField(default=0,decimal_places=2,max_digits=15)

#    approved_by = models.ForeignKey(User,on_delete=models.CASCADE,related_name='approver',default=None)
#    cleared_by = models.ForeignKey(User,on_delete=models.CASCADE,related_name='clearer',default=None)
    added_on = models.DateField(default = timezone.now())
    file = models.FileField(null = True)


class exp_items(models.Model):
    exp = models.ForeignKey(expenditure,on_delete=models.CASCADE)
    desc = models.CharField(max_length=1000)
    price = models.DecimalField(decimal_places=2,max_digits=20,default = 0)
    qty = models.IntegerField(default = 1)
    amount = models.DecimalField(decimal_places=2,max_digits=20)
    


class approved(models.Model):
	exp = models.ForeignKey(expenditure,on_delete=models.CASCADE)
	approved_by = models.ForeignKey(member,on_delete=models.CASCADE,default=None)
	approval_date = models.DateField(timezone.now())
	expense_head = models.CharField(max_length=250)
	category = models.CharField(max_length=250)
	sub_category = models.CharField(max_length=250)
	amount_approved = models.DecimalField(default=0,decimal_places=2,max_digits=15)
	approve_comments = models.CharField(max_length=1000)


class cleared(models.Model):
    exp = models.ForeignKey(expenditure,on_delete=models.CASCADE)
    is_adv = models.BooleanField(default = False)
    cleared_by = models.ForeignKey(member,on_delete=models.CASCADE,default=None)
    cleared_date = models.DateField(timezone.now())
    amount_cleared = models.DecimalField(default=0,decimal_places=2,max_digits=15)
    clear_comments = models.CharField(max_length=1000)

root_web/expenditure/forms.py
from django.forms import ModelForm,Textarea,DecimalField
from .models import expenditure,exp_items,advanced


class add_exp(ModelForm):
    class Meta:
        model = expenditure
        fields = ['event_name','event_desc','event_date','bill_amount','bill_no','bill_date','vendor_name','file']
        widgets = {
            'event_desc': Textarea(attrs={'cols':80,'rows':20}),
        }


class add_adv_form(ModelForm):
    class Meta:
        model = advanced
        fields = ['event_name','adv_desc','event_date','amount']
        widgets = {
            'adv_desc': Textarea(attrs={'cols':80,'rows':20}),
        }

root_web/expenditure/views.py
from django.shortcuts import render
from .forms import add_exp,add_adv_form
from .models import advanced
from usersreg.models import member
#Create your views here.


def add_exp_view(request):
    mem = member.objects.get(user = request.user)
    form = add_exp()
    print(form)
    return render(request,'expenditure/add_exp.html',{'form':form,"member":mem})


#def add_exp_det(request):
#    return render(request,'expenditure/add_exp_det.html')


def generate_exp(request):
    mem = member.objects.get(user = request.user)
    type1 = int(request.POST["type"])
    if type1 == 0:
        mem = member.objects.get(user = request.user)
        adv_obj = advanced(added_by = mem,event_name = request.POST["event_name"], adv_desc = request.POST["adv_desc"],event_date = request.POST["event_date"],amount = request.POST["amount"])
        adv_obj.save()
    if type1 == 1:
        print(request.POST)
        print("expense added")
    return render(request,'expenditure/exp_gen.html',{"type":type1,"member":mem})


def add_adv(request):
    mem = member.objects.get(user = request.user)
    form = add_adv_form()
    print(form)
    return render(request,'expenditure/add_adv.html',{'form':form,"member":mem})


def clear_exp(request):
    mem = member.objects.get(user  = request.user)
    adv_obj = advanced.objects.all()
    print(adv_obj[0].adv_id)
    return render(request,'expenditure/clear_exp.html',{'adv':adv_obj,"member":mem})


def approve_exp(request):
    mem = member.objects.get(user  = request.user)
    return render(request,'expenditure/exp_gen.html',{"member":mem})


def my_exp(request):
    mem = member.objects.get(user  = request.user)
    return render(request,'expenditure/exp_gen.html',{"member":mem})


def view_exp(request):
    mem = member.objects.get(user  = request.user)
    return render(request,'expenditure/exp_gen.html',{"member":mem})

root_web/templates/expenditure/add_adv.html
{% extends 'users/index.html'%}

{% block content%}
<form method="POST">
{% csrf_token %}
<input type="hidden" value="0" name="type">
    <table>
    {{form.as_table}}
</table>
<input type="Submit" value="Submit" formaction="{%url 'expenditure:gen_exp'%}">
</form>

{% endblock %}

root_web/templates/expenditure/add_exp.html
{% extends 'users/index.html' %}
{% block content %}
<style>
    table,td,th{
        border: 1px solid black;
    }
</style>
<form method="POST">
{% csrf_token %}
<input type="hidden" value="1" name="type">
<h1>Expense details</h1>
    <table>
        {{form.as_table}}
    </table>
<h1>Bill Details</h1>
<table id = "main_table">
    <tr>
    <th>Sr No.</th>
    <th>Item</th>
    <th>Quantity</th>
    <th>Price</th>
    </tr>
    <tr>
    <td>1</td>
    <td><input id="item1" name="item1" style="width:200px"></td>
    <td><input id="item1" name="item1" style="width:30px"></td>
    <td><input id="item1" name="item1" style="width:30px"></td>
    </tr>
</table>  
<input type="Submit" value="Submit" formaction="{%url 'expenditure:gen_exp'%}">
<BUTTON type="button" onclick="myFunction()" id="onebut" name="one_but">Add Field</BUTTON> 
</form>
<script>
    var count = 2;
    function myFunction(){
        var table = document.getElementById("main_table");
        var row = table.insertRow(count);
        var cell0 = row.insertCell(0);
        var cell1 = row.insertCell(1);
        var cell2 = row.insertCell(2);
        var cell3 = row.insertCell(3);
        var cell4 = row.insertCell(4);
        cell0.innerHTML = count;
        
        var t1 = document.createElement("input");
        var t2 = document.createElement("input");
        var t3 = document.createElement("input");
        var t4 = document.createElement("BUTTON");
        
        var t = document.createTextNode("Delete");
        t1.name = "item"+count;
        t1.style.width = "200px";
        t2.name = "qty"+count;
        t2.style.width = "30px";
        t3.name = "price"+count;
        t3.style.width = "30px";
        t1.id = "item"+count;
        t2.id = "qty"+count;
        t3.id = "price"+count;
        t4.id = "but"+count;
        t4.appendChild(t);
        t4.type = "button";
        t4.onclick = function () {
            let ind = count-1;
            table.deleteRow(ind);
            count=count-1;
                }   
        cell1.appendChild(t1);
        cell2.appendChild(t2);
        cell3.appendChild(t3);
        cell4.appendChild(t4);
        count++;
    }
</script>
{% endblock %}

root_web/templates/expenditure/add_exp_det.html
{% extends 'users/index.html'%}

{% block content%}
<style>
	table,td,th{
		border: 1px solid black;
	}
</style>

<form method="POST">
{% csrf_token %}
<input type="hidden" value="1" name="type">

<table id = "main_table">
	<tr>
	<th>Sr No.</th>
	<th>Item</th>
	<th>Quantity</th>
	<th>Price</th>
	</tr>
</table>  
<input type="Submit" value="Submit" formaction="{%url 'expenditure:gen_exp'%}">
<BUTTON type="button" onclick="myFunction()" id="onebut" name="one_but">Add Field</BUTTON> 
</form>
<script>
	var count = 1;
	function myFunction(){
		var table = document.getElementById("main_table");
		var row = table.insertRow(count);
		var cell0 = row.insertCell(0);
		var cell1 = row.insertCell(1);
		var cell2 = row.insertCell(2);
		var cell3 = row.insertCell(3);
		var cell4 = row.insertCell(4);
		cell0.innerHTML = count;
		
		var t1 = document.createElement("input");
		var t2 = document.createElement("input");
		var t3 = document.createElement("input");
		var t4 = document.createElement("BUTTON");
		
		var t = document.createTextNode("Delete");
		t1.name = "item"+count;
		t1.style.width = "200px";
		t2.name = "qty"+count;
		t2.style.width = "30px";
		t3.name = "price"+count;
		t3.style.width = "30px";
		t1.id = "item"+count;
		t2.id = "qty"+count;
		t3.id = "price"+count;
		t4.id = "but"+count;
		t4.appendChild(t);
		t4.type = "button";
		t4.onclick = function () {
			let ind = count-1;
  			table.deleteRow(ind);
  			count=count-1;
				}	
		cell1.appendChild(t1);
		cell2.appendChild(t2);
		cell3.appendChild(t3);
		cell4.appendChild(t4);
		count++;
	}
	window.onload = myFunction()
</script>
{% endblock %}

root_web/templates/expenditure/clear_exp.html
{% extends 'users/index.html'%}

{% block content%}
<ul>
{% for obj in adv %}
	<li>{{obj.adv_id}},{{obj.added_by.name}},</li>
{% endfor %}
</ul>
{% endblock %}

root_web/templates/expenditure/exp_gen.html
{% extends 'users/index.html'%}

{% block content%}
{%if type == 0 %}
advanced
{% elif type == 1 %}
expenditure
{% else %}
coming soon
{% endif %}

{% endblock %}

root_web/templates/expenditure/extrascripts.html
<script>
    var prog = ["Education", "Logistics", "Personel Salary","Events","Training"];
    var progvals = ["edu","logs","sal","events","train"];
    var admin = ["Financial and auditing", "Print and Stationary", "Office","Miscellaneous"];
    var adminvals = ["fin","pstat","office","misc"];
    var fund = ["Offline", "Online", "Events"];
    var fundvals = ["offline","online","events"];
    function change(itens,itenvals){
    var selectElem = document.getElementById("id_exp_subhead");
    for (i=selectElem.options.length -1; i>=0; i--){
    selectElem.options[i] = null;}
    for (var i = 0; i < itens.length; i++){
        var item = itens[i];
        var element = document.createElement("option");
        element.innerText = item;
        element.value = itenvals[i]
        selectElem.append(element);
        }}
    function sel(){
        if (document.querySelector('#id_exp_head').value==='prog'){change(prog,progvals);}
        if (document.querySelector('#id_exp_head').value==='admin'){change(admin,adminvals);}
        if (document.querySelector('#id_exp_head').value==='funds'){change(fund,fundvals);}
    }
    document.addEventListener('DOMContentLoaded',function() {document.querySelector('#id_exp_head').onchange=sel})

</script>
<script>
    document.getElementById("id_adv_amount").disabled = true;
        document.getElementById("id_advanced").onchange = function() {
    document.getElementById("id_adv_amount").disabled = !this.checked;}
</script>