root_web/donation/urls.py
from django.urls import path,include
from . import views

app_name = 'donation'

urlpatterns = [
    path('add_don/',views.add_don,name='add_don'),
    path('don_ind/',views.don_ind,name='don_ind'),
    path('don_bulk/',views.don_bulk,name='don_bulk'),
    path('don_anon/',views.don_anon,name='don_anon'),
    path('don_added/',views.don_added,name='don_added'),
    path('view_don/',views.DonationListView.as_view(),name = 'view_don'),
    path('download/',views.download_rec,name = 'download_rec'),
    path('edit_misc/',views.set_prefix,name = 'edit_misc'),
    path('export_donation/',views.export_donation,name = 'export_donations'),
    path('resend_mails/',views.resend_mails,name = 'resend_mail'),
    path('edit_don/',views.edit_don,name = 'edit_don')
]

root_web/root_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='root'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('supp/',include('supporters.urls')),
    path('don/',include('donation.urls')),
    path('exp/',include('expenditure.urls')),
    path('user/',include('usersreg.urls'))
]

root_web/supporters/urls.py
from django.urls import path
from . import views

app_name = 'supporters'
urlpatterns = [
    path('add_supp/',views.add_supp,name = 'add_supp'),
    path('edit_supp/',views.supp_edited,name = 'supp_edited'),
    path('supp_edited/',views.edit_supp,name = 'edit_supp'),
    path('view_supp/',views.view_supp,name = 'view_supp'),
    path('del_supp/',views.del_supp,name = 'del_supp'),
    path('deleted/',views.delete, name='deleted'),
    path('view_don/',views.view_don,name = 'view_don'),
    path('import/',views.import_supp,name = 'import'),
    path('don_details/',views.view_don,name = 'don_details'),
    path('export/',views.export_supporters,name = 'export_supporters')
    ]

root_web/templates/supp/add_supp.html
{% extends 'users/index.html' %}
{% block content %}
{% if messages == '0' %}
{% else %}
<script>
    alert('{{ messages }}');
</script>
{% endif %}
<form action="{% url 'supporters:add_supp' %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    <tr>
        <th><label for="dob">Date of Birth:</label></th>
        <td><input type="date" id="dob" name="dob"></td>
    </tr>
    </table>
    <input type="submit" value="Submit">

</form>
    <script>
      document.getElementById("id_is_constant").onchange = function(){
      document.getElementById("id_amount").disabled = !this.checked;
      }
      document.getElementById("id_is_sponsor").onchange = function(){
      document.getElementById("id_sponsee").disabled = !this.checked;
      }
      document.getElementById("id_is_si").onchange = function(){
      document.getElementById("id_si_date").disabled = !this.checked;
      document.getElementById("id_amount").disabled = !this.checked;
      }
    </script>
{% endblock %}

root_web/templates/supp/deleted.html
{% extends 'users/index.html'%}
{% block content %}
Member Deleted Successfully ;(
{% endblock %}

root_web/templates/supp/detail.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table, th, td{
    border:1px solid black;
    }
    td,th {
    padding:5px;
    }
</style>
<h1>
    Supporter Details
</h1>
<form method="POST">
    {% csrf_token %}
<table >

    <input type="text" name="phone" hidden value="{{ supp.phone_no }}">
    <tr>
        <th>Name</th>
        <td>{{supp.name}}</td>
    </tr>
    <tr>
        <th>Age</th>
        <td>{{supp.age}}</td>
    </tr>
    <tr>
        <th>Phone</th>
        <td>{{supp.phone_no}}</td>
    </tr>
    <tr>
        <th>Gender</th>
        <td>{{supp.gender}}</td>
    </tr>
    <tr>
        <th>Alt Phone No</th>
        <td>{{supp.alt_phone_no}}</td>
    </tr>
    <tr>
        <th>Email Id</th>
        <td>{{supp.email_id}}</td>
    </tr>
    <tr>
        <th>City</th>
        <td>{{supp.city}}</td>
    </tr>
    <tr>
        <th>Reference</th>
        <td>{{supp.Reference}}</td>
    </tr>
    <tr>
        <th>Pan Card</th>
        <td>{{supp.pan_card}}</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>{{supp.address_a}}</td>
    </tr>
    <tr>
        <th>Type</th>
        <td>
            {% if supp.is_constantv%}
            Constant,
            {% endif %}
            {% if supp.is_resources %}
            Resources,
            {% endif %}
            {% if supp.is_sponsor %}
            Sponsor,
            {% endif %}
            {% if supp.is_si %}
            SI,
            {% endif %}
            {% if supp.is_one_time %}
            One Time,
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>Amount</th>
        <td>{{supp.amount}}</td>
    </tr>
    <tr>
        <th>SI_Date</th>
        <td>{{supp.si_date}}</td>
    </tr>
    <tr>
        <th>Profession</th>
        <td>{{supp.profession}}</td>
    </tr>
    <tr>
        <th>DOB</th>
        <td>{{supp.dob}}</td>
    </tr>
    <tr>
        <th>Verified</th>
        <td>{{supp.is_verified}}</td>
    </tr>
    <tr>
        <th>Last Donation Generated</th>
        <td>{{supp.last_generated}}</td>
    </tr>
    <tr>
        <th>Date Added</th>
        <td>{{supp.date_added}}</td>
    </tr>
    <tr>
        <th>Last Edited</th>
        <td>{{supp.date_edited}}</td>
    </tr>
</table>
{% if view == 'delete' %}
<input type="submit" formaction="{% url 'supporters:deleted' %}" value="Delete">
{% endif %}
{% if view == 'details' %}
<input type="submit" formaction="{% url 'supporters:don_details' %}" value="Donations">
{% endif %}
</form>
{% endblock %}

root_web/templates/supp/edit_spp.html
{% extends 'users/index.html' %}
{% block content %}
<form  method="POST">
{% csrf_token %}
<label for="name">Name</label>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
{% for choice in supp%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
{% if view == 'edit' %}
<input type="submit" formaction="{% url 'supporters:edit_supp'%}" value="Edit">
{% endif %}
{% if view == 'details' %}
<input type="submit" formaction="{% url 'supporters:view_supp'%}" value="Details">
{% endif  %}
{% if view == 'delete' %}
<input type="submit" formaction="{% url 'supporters:view_supp'%}" value="Details">
{% endif  %}
</form>
{% endblock %}

root_web/templates/supp/edit_supp_form.html
{% extends 'users/index.html' %}
{% block content %}
{% if messages == '0' %}
{% else %}
<script>
    alert('{{ messages }}');
</script>
{% endif %}
<form action="{% url 'supporters:supp_edited' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="pk" id="pk" value="{{obj.pk}}">
    <table>
    {{ form.as_table }}
    <tr>
        <th><label for="dob">Date of Birth:</label></th>
        <td><input type="date" id="dob" name="dob"></td>
    </tr>
    </table>
    <input type="submit" value="Submit">

</form>
    <script>
      document.getElementById("id_is_constant").onchange = function(){
      document.getElementById("id_amount").disabled = !this.checked;
      }
      document.getElementById("id_is_sponsor").onchange = function(){
      document.getElementById("id_sponsee").disabled = !this.checked;
      }
      document.getElementById("id_is_si").onchange = function(){
      document.getElementById("id_si_date").disabled = !this.checked;
      document.getElementById("id_amount").disabled = !this.checked;
      }
    </script>
{% endblock %}

root_web/templates/supp/import.html
{% extends 'users/index.html' %}
{% block content %}
<form action="{% url 'supporters:import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>
{% endblock %}

root_web/templates/supp/supp_edited.html
{% extends 'users/index.html' %}
{% block content %}
<p>Member edited successfully</p>
{%endblock%}